
services:
  postgres:
    image: postgres:13
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - airflow-net
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.1
    command: standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - _AIRFLOW_WWW_USER_USERNAME= ${_AIRFLOW_WWW_USER_USERNAME}
      - _AIRFLOW_WWW_USER_PASSWORD= ${_AIRFLOW_WWW_USER_PASSWORD}
      - _AIRFLOW_WWW_USER_FIRSTNAME= ${_AIRFLOW_WWW_USER_FIRSTNAME}
      - _AIRFLOW_WWW_USER_LASTNAME= ${_AIRFLOW_WWW_USER_LASTNAME}
      - _AIRFLOW_WWW_USER_ROLE= ${_AIRFLOW_WWW_USER_ROLE}
      - _AIRFLOW_WWW_USER_EMAIL= ${_AIRFLOW_WWW_USER_EMAIL}
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - .:/opt/airflow/project  # Додаємо весь проєкт у контейнер:/opt/airflow/plugins
    depends_on:
      - postgres
    networks:
      - airflow-net
    

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=secret-key
    depends_on:
      - postgres
    volumes:
      - ./superset_home:/app/superset_home


networks:
  airflow-net:
    driver: bridge
volumes:
  postgres_data:
  superset_home:
  